---
abstract: 'COUNTER Codes of Practice report processing'
author:
  - 'Paul Hoffman <nkuitse@cpan.org>'
  - 'Todd Holbrook <holbrook@cpan.org>'
  - 'Helge Knüttel <helge.knuettel@ur.de>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Biblio-COUNTER
provides:
  Biblio::COUNTER:
    file: lib/Biblio/COUNTER.pm
    version: 0.14
  Biblio::COUNTER::Processor:
    file: lib/Biblio/COUNTER/Processor.pm
  Biblio::COUNTER::Processor::Atomize:
    file: lib/Biblio/COUNTER/Processor/Atomize.pm
  Biblio::COUNTER::Processor::Simple:
    file: lib/Biblio/COUNTER/Processor/Simple.pm
  Biblio::COUNTER::Processor::Validate:
    file: lib/Biblio/COUNTER/Processor/Validate.pm
  Biblio::COUNTER::Report:
    file: lib/Biblio/COUNTER/Report.pm
  Biblio::COUNTER::Report::Release2::DatabaseReport1:
    file: lib/Biblio/COUNTER/Report/Release2/DatabaseReport1.pm
  Biblio::COUNTER::Report::Release2::DatabaseReport2:
    file: lib/Biblio/COUNTER/Report/Release2/DatabaseReport2.pm
  Biblio::COUNTER::Report::Release2::DatabaseReport3:
    file: lib/Biblio/COUNTER/Report/Release2/DatabaseReport3.pm
  Biblio::COUNTER::Report::Release2::JournalReport1:
    file: lib/Biblio/COUNTER/Report/Release2/JournalReport1.pm
  Biblio::COUNTER::Report::Release2::JournalReport1a:
    file: lib/Biblio/COUNTER/Report/Release2/JournalReport1a.pm
  Biblio::COUNTER::Report::Release2::JournalReport2:
    file: lib/Biblio/COUNTER/Report/Release2/JournalReport2.pm
  Biblio::COUNTER::Report::Release3::JournalReport1:
    file: lib/Biblio/COUNTER/Report/Release3/JournalReport1.pm
  Biblio::COUNTER::Report::Release3::JournalReport1a:
    file: lib/Biblio/COUNTER/Report/Release3/JournalReport1a.pm
  Biblio::COUNTER::Report::Release4::JournalReport1:
    file: lib/Biblio/COUNTER/Report/Release4/JournalReport1.pm
requires:
  Log::Log4perl: 0
  Text::CSV: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
